# Generated by Django 5.2 on 2025-05-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
