# Generated by Django 5.2 on 2025-05-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstatus_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Booked', 'Booked')], default='Available', max_length=10),
        ),
    ]
